// ============================================================
// Telal Development — Static Demo Data
// Used for development before database is connected
// ============================================================

import {
  type Property,
  type Project,
  type BlogPost,
  type FAQ,
  type Testimonial,
  type TeamMember,
  type Service,
  type MeetingRoom,
  PropertyType,
  PropertyStatus,
  ProjectStatus,
} from "../types";

// ── Properties ────────────────────────────────────────────
export const properties: Property[] = [
  {
    id: "prop-1",
    slug: "al-thuraya-tower-penthouse",
    title: "Al Thuraya Tower Penthouse",
    titleAr: "بنتهاوس برج الثريا",
    description: "An extraordinary penthouse spanning the top two floors of Al Thuraya Tower, offering panoramic views of the Riyadh skyline. This residence features floor-to-ceiling windows, imported Italian marble, a private elevator, and a rooftop terrace with an infinity pool. The epitome of luxury living in the heart of Olaya District.",
    descriptionAr: "بنتهاوس استثنائي يمتد على الطابقين العلويين من برج الثريا، يوفر إطلالات بانورامية على أفق الرياض. يتميز بنوافذ من الأرض إلى السقف ورخام إيطالي مستورد ومصعد خاص وشرفة على السطح مع مسبح لا متناهي.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 12500000,
    currency: "SAR",
    area: 650,
    bedrooms: 5,
    bathrooms: 7,
    floors: 2,
    parkingSpots: 4,
    location: "Olaya District, King Fahd Road",
    city: "Riyadh",
    coordinates: { lat: 24.6908, lng: 46.6854 },
    amenities: ["Swimming Pool", "Gym", "Spa", "Concierge", "Smart Home", "Rooftop", "Parking", "Security"],
    images: [
      { id: "img-1", url: "/images/properties/penthouse-1.jpg", alt: "Al Thuraya Penthouse Living Room", order: 0, propertyId: "prop-1" },
      { id: "img-2", url: "/images/properties/penthouse-2.jpg", alt: "Al Thuraya Penthouse Bedroom", order: 1, propertyId: "prop-1" },
    ],
    videos: [],
    floorPlans: [],
    projectId: "proj-1",
    isFeatured: true,
    isPublished: true,
    views: 2847,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "prop-2",
    slug: "rimal-gardens-villa",
    title: "Rimal Gardens Villa",
    titleAr: "فيلا حدائق الرمال",
    description: "A masterfully designed villa in the prestigious Rimal Gardens compound, blending contemporary architecture with traditional Arabian elements.",
    descriptionAr: "فيلا مصممة بإتقان في مجمع حدائق الرمال المرموق، تمزج بين العمارة المعاصرة والعناصر العربية التقليدية.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 8750000,
    currency: "SAR",
    area: 520,
    bedrooms: 6,
    bathrooms: 5,
    floors: 2,
    parkingSpots: 3,
    location: "Al Nakheel District",
    city: "Riyadh",
    coordinates: { lat: 24.7241, lng: 46.6527 },
    amenities: ["Garden", "Parking", "Smart Home", "Security", "Maid Room", "Children's Play Area", "BBQ Area"],
    images: [
      { id: "img-3", url: "/images/properties/villa-1.jpg", alt: "Rimal Gardens Villa Exterior", order: 0, propertyId: "prop-2" },
    ],
    videos: [],
    floorPlans: [],
    isFeatured: true,
    isPublished: true,
    views: 1923,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "prop-3",
    slug: "noor-residences-3br",
    title: "Noor Residences — 3 Bedroom",
    titleAr: "نور ريزيدنسز — 3 غرف نوم",
    description: "Modern luxury apartment in the iconic Noor Residences development. Thoughtfully designed with an open-plan living concept, premium finishes, and stunning city views.",
    descriptionAr: "شقة فاخرة عصرية في مشروع نور ريزيدنسز الأيقوني. مصممة بعناية بمفهوم مفتوح وتشطيبات فاخرة وإطلالات مدنية خلابة.",
    type: PropertyType.OFF_PLAN,
    status: PropertyStatus.OFF_PLAN,
    price: 3200000,
    currency: "SAR",
    area: 245,
    bedrooms: 3,
    bathrooms: 4,
    floors: 1,
    parkingSpots: 2,
    location: "King Abdullah Financial District",
    city: "Riyadh",
    coordinates: { lat: 24.7648, lng: 46.6450 },
    amenities: ["Swimming Pool", "Gym", "Spa", "Concierge", "Elevator", "Parking", "Security", "Lobby"],
    images: [
      { id: "img-4", url: "/images/properties/apartment-1.jpg", alt: "Noor Residences Living Area", order: 0, propertyId: "prop-3" },
    ],
    videos: [],
    floorPlans: [],
    projectId: "proj-2",
    isFeatured: true,
    isPublished: true,
    views: 3456,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-04-01"),
  },
  {
    id: "prop-4",
    slug: "corniche-bay-duplex",
    title: "Corniche Bay Duplex",
    titleAr: "دوبلكس كورنيش باي",
    description: "Stunning waterfront duplex with direct views of the Jeddah Corniche. Features floor-to-ceiling windows, a wraparound terrace, and direct beach access.",
    descriptionAr: "دوبلكس مذهل على الواجهة البحرية مع إطلالات مباشرة على كورنيش جدة.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 6800000,
    currency: "SAR",
    area: 380,
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    parkingSpots: 2,
    location: "Al Corniche",
    city: "Jeddah",
    coordinates: { lat: 21.5433, lng: 39.1728 },
    amenities: ["Swimming Pool", "Gym", "Balcony", "Parking", "Security", "Concierge"],
    images: [
      { id: "img-5", url: "/images/properties/duplex-1.jpg", alt: "Corniche Bay Duplex View", order: 0, propertyId: "prop-4" },
    ],
    videos: [],
    floorPlans: [],
    isFeatured: true,
    isPublished: true,
    views: 2134,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-28"),
  },
  {
    id: "prop-5",
    slug: "telal-business-park-office",
    title: "Telal Business Park — Grade A Office",
    titleAr: "تلال بزنس بارك — مكتب درجة أولى",
    description: "Premium Grade A office space in Telal Business Park, the kingdom's most prestigious commercial address.",
    descriptionAr: "مساحة مكتبية فاخرة من الدرجة الأولى في تلال بزنس بارك، العنوان التجاري الأرقى في المملكة.",
    type: PropertyType.COMMERCIAL,
    status: PropertyStatus.AVAILABLE,
    price: 15000000,
    currency: "SAR",
    area: 1200,
    floors: 3,
    parkingSpots: 20,
    location: "KAFD",
    city: "Riyadh",
    coordinates: { lat: 24.7648, lng: 46.6450 },
    amenities: ["Parking", "Security", "Concierge", "Elevator", "Lobby"],
    images: [
      { id: "img-6", url: "/images/properties/office-1.jpg", alt: "Telal Business Park Office", order: 0, propertyId: "prop-5" },
    ],
    videos: [],
    floorPlans: [],
    projectId: "proj-3",
    isFeatured: false,
    isPublished: true,
    views: 987,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "prop-6",
    slug: "sahara-heights-studio",
    title: "Sahara Heights — Luxury Studio",
    titleAr: "صحراء هايتس — استوديو فاخر",
    description: "Efficiently designed luxury studio in Sahara Heights, perfect for young professionals and investors.",
    descriptionAr: "استوديو فاخر مصمم بكفاءة في صحراء هايتس، مثالي للمهنيين الشباب والمستثمرين.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 850000,
    currency: "SAR",
    area: 65,
    bedrooms: 0,
    bathrooms: 1,
    parkingSpots: 1,
    location: "Al Malqa District",
    city: "Riyadh",
    coordinates: { lat: 24.8004, lng: 46.6272 },
    amenities: ["Gym", "Parking", "Smart Home", "Security", "Elevator"],
    images: [
      { id: "img-7", url: "/images/properties/studio-1.jpg", alt: "Sahara Heights Studio", order: 0, propertyId: "prop-6" },
    ],
    videos: [],
    floorPlans: [],
    isFeatured: false,
    isPublished: true,
    views: 1456,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-04-05"),
  },
];

// ── Projects ──────────────────────────────────────────────
export const projects: Project[] = [
  {
    id: "proj-1",
    slug: "al-thuraya-tower",
    name: "Al Thuraya Tower",
    nameAr: "برج الثريا",
    description: "A 45-story landmark tower redefining the Riyadh skyline.",
    type: "Residential Tower",
    status: ProjectStatus.COMPLETED,
    location: "Olaya District, Riyadh",
    launchDate: new Date("2020-06-01"),
    completionDate: new Date("2023-12-01"),
    totalUnits: 120,
    coverImage: "/images/projects/thuraya-cover.jpg",
    gallery: ["/images/projects/thuraya-1.jpg", "/images/projects/thuraya-2.jpg"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2020-06-01"),
  },
  {
    id: "proj-2",
    slug: "noor-residences",
    name: "Noor Residences",
    nameAr: "نور ريزيدنسز",
    description: "A visionary mixed-use development in King Abdullah Financial District.",
    type: "Mixed-Use Development",
    status: ProjectStatus.UNDER_CONSTRUCTION,
    location: "KAFD, Riyadh",
    launchDate: new Date("2023-03-01"),
    completionDate: new Date("2026-06-01"),
    totalUnits: 340,
    coverImage: "/images/projects/noor-cover.jpg",
    gallery: ["/images/projects/noor-1.jpg", "/images/projects/noor-2.jpg"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "proj-3",
    slug: "telal-business-park",
    name: "Telal Business Park",
    nameAr: "تلال بزنس بارك",
    description: "The Kingdom's most prestigious commercial address.",
    type: "Commercial Complex",
    status: ProjectStatus.PLANNING,
    location: "KAFD, Riyadh",
    launchDate: new Date("2024-09-01"),
    completionDate: new Date("2028-12-01"),
    totalUnits: 45,
    coverImage: "/images/projects/business-cover.jpg",
    gallery: ["/images/projects/business-1.jpg"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
  },
];

// ── Blog Posts ─────────────────────────────────────────────
export const blogPosts: BlogPost[] = [
  {
    id: "blog-1",
    slug: "saudi-luxury-real-estate-2024-outlook",
    title: "Saudi Luxury Real Estate: 2024 Market Outlook",
    titleAr: "العقارات الفاخرة في السعودية: توقعات السوق لعام 2024",
    excerpt: "The Kingdom's luxury real estate sector continues its unprecedented growth trajectory.",
    body: "The Saudi Arabian luxury real estate market has entered a golden era...",
    coverImage: "/images/blog/market-outlook.jpg",
    category: "Market Analysis",
    tags: ["market analysis", "luxury", "investment", "Vision 2030"],
    author: "Ahmed Al-Rashid",
    readTime: 8,
    isPublished: true,
    publishedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "blog-2",
    slug: "sustainable-luxury-future-of-development",
    title: "Sustainable Luxury: The Future of Real Estate Development",
    titleAr: "الفخامة المستدامة: مستقبل التطوير العقاري",
    excerpt: "How Telal Development is pioneering eco-conscious luxury.",
    body: "Sustainability and luxury are no longer opposing concepts...",
    coverImage: "/images/blog/sustainability.jpg",
    category: "Sustainability",
    tags: ["sustainability", "green building", "LEED", "innovation"],
    author: "Sarah Al-Mutairi",
    readTime: 6,
    isPublished: true,
    publishedAt: new Date("2024-02-28"),
    createdAt: new Date("2024-02-25"),
  },
];

// ── Meeting Rooms ─────────────────────────────────────────
export const meetingRooms: MeetingRoom[] = [
  {
    id: "room-1",
    name: "The Boardroom",
    capacity: 16,
    amenities: ["Video Conferencing", "Whiteboard", "Coffee Service", "Sound System", "Projector"],
    imageUrl: "/images/rooms/boardroom.jpg",
    floor: 25,
    isActive: true,
  },
  {
    id: "room-2",
    name: "The Innovation Suite",
    capacity: 8,
    amenities: ["Smart TV", "Whiteboard", "Coffee Service", "High-Speed WiFi"],
    imageUrl: "/images/rooms/innovation.jpg",
    floor: 25,
    isActive: true,
  },
];

// ── Available Time Slots ──────────────────────────────────
export const timeSlots = [
  "09:00", "09:30", "10:00", "10:30", "11:00", "11:30",
  "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
  "15:00", "15:30", "16:00", "16:30", "17:00",
];
