// ============================================================
// Telal Development — Static Demo Data
// Used for development before database is connected
// ============================================================

import {
  type Property,
  type Project,
  type BlogPost,
  type FAQ,
  type Testimonial,
  type TeamMember,
  type Service,
  type MeetingRoom,
  PropertyType,
  PropertyStatus,
  ProjectStatus,
} from "@/types";

// ── Properties ────────────────────────────────────────────
export const properties: Property[] = [
  {
    id: "prop-1",
    slug: "al-thuraya-tower-penthouse",
    title: "Al Thuraya Tower Penthouse",
    titleAr: "بنتهاوس برج الثريا",
    description: "An extraordinary penthouse spanning the top two floors of Al Thuraya Tower, offering panoramic views of the Riyadh skyline. This residence features floor-to-ceiling windows, imported Italian marble, a private elevator, and a rooftop terrace with an infinity pool. The epitome of luxury living in the heart of Olaya District.",
    descriptionAr: "بنتهاوس استثنائي يمتد على الطابقين العلويين من برج الثريا، يوفر إطلالات بانورامية على أفق الرياض. يتميز بنوافذ من الأرض إلى السقف ورخام إيطالي مستورد ومصعد خاص وشرفة على السطح مع مسبح لا متناهي.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 12500000,
    currency: "SAR",
    area: 650,
    bedrooms: 5,
    bathrooms: 7,
    floors: 2,
    parkingSpots: 4,
    location: "Olaya District, King Fahd Road",
    city: "Riyadh",
    coordinates: { lat: 24.6908, lng: 46.6854 },
    amenities: ["Swimming Pool", "Gym", "Spa", "Concierge", "Smart Home", "Rooftop", "Parking", "Security"],
    images: [
      { id: "img-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", alt: "Al Thuraya Penthouse Living Room", order: 0, propertyId: "prop-1" },
      { id: "img-2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80", alt: "Al Thuraya Penthouse Bedroom", order: 1, propertyId: "prop-1" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    projectId: "proj-1",
    isFeatured: true,
    isPublished: true,
    views: 2847,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "prop-2",
    slug: "rimal-gardens-villa",
    title: "Rimal Gardens Villa",
    titleAr: "فيلا حدائق الرمال",
    description: "A masterfully designed villa in the prestigious Rimal Gardens compound, blending contemporary architecture with traditional Arabian elements. Features include a private garden with mature landscaping, separate majlis, home theater, and smart home automation throughout.",
    descriptionAr: "فيلا مصممة بإتقان في مجمع حدائق الرمال المرموق، تمزج بين العمارة المعاصرة والعناصر العربية التقليدية. تشمل حديقة خاصة ومجلس منفصل وغرفة سينما منزلية ونظام أتمتة ذكي.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 8750000,
    currency: "SAR",
    area: 520,
    bedrooms: 6,
    bathrooms: 5,
    floors: 2,
    parkingSpots: 3,
    location: "Al Nakheel District",
    city: "Riyadh",
    coordinates: { lat: 24.7241, lng: 46.6527 },
    amenities: ["Garden", "Parking", "Smart Home", "Security", "Maid Room", "Children's Play Area", "BBQ Area"],
    images: [
      { id: "img-3", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80", alt: "Rimal Gardens Villa Exterior", order: 0, propertyId: "prop-2" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: true,
    isPublished: true,
    views: 1923,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "prop-3",
    slug: "noor-residences-3br",
    title: "Noor Residences — 3 Bedroom",
    titleAr: "نور ريزيدنسز — 3 غرف نوم",
    description: "Modern luxury apartment in the iconic Noor Residences development. Thoughtfully designed with an open-plan living concept, premium finishes, and stunning city views. Residents enjoy exclusive access to world-class amenities including a rooftop infinity pool and private cinema.",
    descriptionAr: "شقة فاخرة عصرية في مشروع نور ريزيدنسز الأيقوني. مصممة بعناية بمفهوم مفتوح وتشطيبات فاخرة وإطلالات مدنية خلابة.",
    type: PropertyType.OFF_PLAN,
    status: PropertyStatus.OFF_PLAN,
    price: 3200000,
    currency: "SAR",
    area: 245,
    bedrooms: 3,
    bathrooms: 4,
    floors: 1,
    parkingSpots: 2,
    location: "King Abdullah Financial District",
    city: "Riyadh",
    coordinates: { lat: 24.7648, lng: 46.6450 },
    amenities: ["Swimming Pool", "Gym", "Spa", "Concierge", "Elevator", "Parking", "Security", "Lobby"],
    images: [
      { id: "img-4", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", alt: "Noor Residences Living Area", order: 0, propertyId: "prop-3" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    projectId: "proj-2",
    isFeatured: true,
    isPublished: true,
    views: 3456,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-04-01"),
  },
  {
    id: "prop-4",
    slug: "corniche-bay-duplex",
    title: "Corniche Bay Duplex",
    titleAr: "دوبلكس كورنيش باي",
    description: "Stunning waterfront duplex with direct views of the Jeddah Corniche. Features floor-to-ceiling windows, a wraparound terrace, gourmet kitchen with Gaggenau appliances, and direct beach access. A rare gem on the Red Sea coast.",
    descriptionAr: "دوبلكس مذهل على الواجهة البحرية مع إطلالات مباشرة على كورنيش جدة. نوافذ من الأرض للسقف وشرفة محيطية ومطبخ فاخر.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 6800000,
    currency: "SAR",
    area: 380,
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    parkingSpots: 2,
    location: "Al Corniche",
    city: "Jeddah",
    coordinates: { lat: 21.5433, lng: 39.1728 },
    amenities: ["Swimming Pool", "Gym", "Balcony", "Parking", "Security", "Concierge"],
    images: [
      { id: "img-5", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80", alt: "Corniche Bay Duplex View", order: 0, propertyId: "prop-4" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: true,
    isPublished: true,
    views: 2134,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-28"),
  },
  {
    id: "prop-5",
    slug: "telal-business-park-office",
    title: "Telal Business Park — Grade A Office",
    titleAr: "تلال بزنس بارك — مكتب درجة أولى",
    description: "Premium Grade A office space in Telal Business Park, the kingdom's most prestigious commercial address. Features include state-of-the-art building management systems, 24/7 concierge service, underground parking, and direct metro connectivity.",
    descriptionAr: "مساحة مكتبية فاخرة من الدرجة الأولى في تلال بزنس بارك، العنوان التجاري الأرقى في المملكة.",
    type: PropertyType.COMMERCIAL,
    status: PropertyStatus.AVAILABLE,
    price: 15000000,
    currency: "SAR",
    area: 1200,
    floors: 3,
    parkingSpots: 20,
    location: "KAFD",
    city: "Riyadh",
    coordinates: { lat: 24.7648, lng: 46.6450 },
    amenities: ["Parking", "Security", "Concierge", "Elevator", "Lobby"],
    images: [
      { id: "img-6", url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80", alt: "Telal Business Park Office", order: 0, propertyId: "prop-5" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    projectId: "proj-3",
    isFeatured: false,
    isPublished: true,
    views: 987,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "prop-6",
    slug: "sahara-heights-studio",
    title: "Sahara Heights — Luxury Studio",
    titleAr: "صحراء هايتس — استوديو فاخر",
    description: "Efficiently designed luxury studio in Sahara Heights, perfect for young professionals and investors. Premium finishes, smart home features, and access to resort-style amenities. Excellent rental yield potential.",
    descriptionAr: "استوديو فاخر مصمم بكفاءة في صحراء هايتس، مثالي للمهنيين الشباب والمستثمرين.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 850000,
    currency: "SAR",
    area: 65,
    bedrooms: 0,
    bathrooms: 1,
    parkingSpots: 1,
    location: "Al Malqa District",
    city: "Riyadh",
    coordinates: { lat: 24.8004, lng: 46.6272 },
    amenities: ["Gym", "Parking", "Smart Home", "Security", "Elevator"],
    images: [
      { id: "img-7", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80", alt: "Sahara Heights Studio", order: 0, propertyId: "prop-6" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: false,
    isPublished: true,
    views: 1456,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-04-05"),
  },
  {
    id: "prop-7",
    slug: "al-waha-compound-villa",
    title: "Al Waha Compound — Executive Villa",
    titleAr: "مجمع الواحة — فيلا تنفيذية",
    description: "Spacious executive villa within the gated Al Waha Compound. Features lush gardens, private pool, staff quarters, and 24-hour security. Ideal for diplomatic families seeking privacy and luxury.",
    descriptionAr: "فيلا تنفيذية واسعة داخل مجمع الواحة المسوّر. تتميز بحدائق خضراء ومسبح خاص وسكن للخدم وأمن على مدار الساعة.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.SOLD,
    price: 7200000,
    currency: "SAR",
    area: 480,
    bedrooms: 5,
    bathrooms: 6,
    floors: 2,
    parkingSpots: 3,
    location: "Diplomatic Quarter",
    city: "Riyadh",
    coordinates: { lat: 24.6614, lng: 46.6247 },
    amenities: ["Swimming Pool", "Garden", "Parking", "Security", "Maid Room", "Smart Home"],
    images: [
      { id: "img-8", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80", alt: "Al Waha Compound Villa", order: 0, propertyId: "prop-7" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: false,
    isPublished: true,
    views: 876,
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prop-8",
    slug: "marina-walk-retail",
    title: "Marina Walk — Premium Retail Space",
    titleAr: "مارينا ووك — مساحة تجزئة فاخرة",
    description: "Prime retail space on Marina Walk, Jeddah's premier waterfront promenade. High foot traffic, double-height ceilings, and premium visibility. Ideal for luxury brands and flagship stores.",
    descriptionAr: "مساحة تجزئة مميزة على مارينا ووك، الممشى الرئيسي على الواجهة البحرية في جدة.",
    type: PropertyType.RETAIL,
    status: PropertyStatus.AVAILABLE,
    price: 4500000,
    currency: "SAR",
    area: 300,
    floors: 2,
    parkingSpots: 5,
    location: "Al Corniche",
    city: "Jeddah",
    coordinates: { lat: 21.5285, lng: 39.1623 },
    amenities: ["Parking", "Security", "Lobby"],
    images: [
      { id: "img-9", url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80", alt: "Marina Walk Retail Space", order: 0, propertyId: "prop-8" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: false,
    isPublished: true,
    views: 654,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "prop-9",
    slug: "the-oasis-resort-suite",
    title: "The Oasis — Resort Suite",
    titleAr: "الواحة — جناح منتجع",
    description: "Exclusive investment opportunity in The Oasis luxury resort development. Fully furnished resort suite with guaranteed rental returns, managed by an international hospitality brand. Includes access to world-class spa, dining, and leisure facilities.",
    descriptionAr: "فرصة استثمارية حصرية في مشروع منتجع الواحة الفاخر. جناح منتجع مفروش بالكامل مع عوائد إيجارية مضمونة.",
    type: PropertyType.HOSPITALITY,
    status: PropertyStatus.OFF_PLAN,
    price: 2100000,
    currency: "SAR",
    area: 120,
    bedrooms: 1,
    bathrooms: 2,
    parkingSpots: 1,
    location: "Red Sea Coast",
    city: "Jeddah",
    coordinates: { lat: 22.3285, lng: 39.0968 },
    amenities: ["Swimming Pool", "Spa", "Gym", "Concierge", "Security"],
    images: [
      { id: "img-10", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80", alt: "The Oasis Resort Suite", order: 0, propertyId: "prop-9" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: true,
    isPublished: true,
    views: 2987,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-04-01"),
  },
  {
    id: "prop-10",
    slug: "khalidiya-tower-2br",
    title: "Khalidiya Tower — 2 Bedroom Apartment",
    titleAr: "برج الخالدية — شقة غرفتين",
    description: "Elegant two-bedroom apartment in the landmark Khalidiya Tower. Modern open-plan design with high-end finishes, integrated kitchen, and expansive balcony. Located in the Eastern Province's most desirable address.",
    descriptionAr: "شقة أنيقة بغرفتي نوم في برج الخالدية المميز. تصميم عصري مفتوح بتشطيبات راقية.",
    type: PropertyType.RESIDENTIAL,
    status: PropertyStatus.AVAILABLE,
    price: 1650000,
    currency: "SAR",
    area: 155,
    bedrooms: 2,
    bathrooms: 3,
    parkingSpots: 1,
    location: "Al Khobar Corniche",
    city: "Eastern Province",
    coordinates: { lat: 26.2172, lng: 50.1971 },
    amenities: ["Gym", "Swimming Pool", "Balcony", "Parking", "Security", "Elevator"],
    images: [
      { id: "img-11", url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80", alt: "Khalidiya Tower Apartment", order: 0, propertyId: "prop-10" },
    ],
    videos: [],
    floorPlans: ["https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80"],
    isFeatured: false,
    isPublished: true,
    views: 1123,
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-03-25"),
  },
];

// ── Projects ──────────────────────────────────────────────
export const projects: Project[] = [
  {
    id: "proj-1",
    slug: "al-thuraya-tower",
    name: "Al Thuraya Tower",
    nameAr: "برج الثريا",
    description: "A 45-story landmark tower redefining the Riyadh skyline. Al Thuraya Tower offers ultra-luxury residences with world-class amenities, concierge services, and panoramic city views. Designed by internationally acclaimed architects, this development represents the pinnacle of urban luxury living in the Kingdom.",
    type: "Residential Tower",
    status: ProjectStatus.COMPLETED,
    location: "Olaya District, Riyadh",
    launchDate: new Date("2020-06-01"),
    completionDate: new Date("2023-12-01"),
    totalUnits: 120,
    coverImage: "https://images.unsplash.com/photo-1577587230708-187fdbef4d91?w=800&q=80",
    gallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2020-06-01"),
  },
  {
    id: "proj-2",
    slug: "noor-residences",
    name: "Noor Residences",
    nameAr: "نور ريزيدنسز",
    description: "A visionary mixed-use development in King Abdullah Financial District. Noor Residences combines premium apartments, retail spaces, and landscaped communal areas in a masterfully planned community. Smart building technology and sustainable design principles are woven into every detail.",
    type: "Mixed-Use Development",
    status: ProjectStatus.UNDER_CONSTRUCTION,
    location: "KAFD, Riyadh",
    launchDate: new Date("2023-03-01"),
    completionDate: new Date("2026-06-01"),
    totalUnits: 340,
    coverImage: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&q=80",
    gallery: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "proj-3",
    slug: "telal-business-park",
    name: "Telal Business Park",
    nameAr: "تلال بزنس بارك",
    description: "The Kingdom's most prestigious commercial address. Telal Business Park comprises Grade A office towers, a conference center, retail podium, and landscaped plazas. Designed for multinational corporations and regional headquarters, with direct metro connectivity and world-class building management systems.",
    type: "Commercial Complex",
    status: ProjectStatus.PLANNING,
    location: "KAFD, Riyadh",
    launchDate: new Date("2024-09-01"),
    completionDate: new Date("2028-12-01"),
    totalUnits: 45,
    coverImage: "https://images.unsplash.com/photo-1554435493-93422e8220c8?w=800&q=80",
    gallery: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
    isPublished: true,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
  },
];

// ── Blog Posts ─────────────────────────────────────────────
export const blogPosts: BlogPost[] = [
  {
    id: "blog-1",
    slug: "saudi-luxury-real-estate-2024-outlook",
    title: "Saudi Luxury Real Estate: 2024 Market Outlook",
    titleAr: "العقارات الفاخرة في السعودية: توقعات السوق لعام 2024",
    excerpt: "The Kingdom's luxury real estate sector continues its unprecedented growth trajectory, driven by Vision 2030 mega-projects and increasing international investor confidence.",
    body: "The Saudi Arabian luxury real estate market has entered a golden era...",
    coverImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    category: "Market Analysis",
    tags: ["market analysis", "luxury", "investment", "Vision 2030"],
    author: "Ahmed Al-Rashid",
    readTime: 8,
    isPublished: true,
    publishedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "blog-2",
    slug: "sustainable-luxury-future-of-development",
    title: "Sustainable Luxury: The Future of Real Estate Development",
    titleAr: "الفخامة المستدامة: مستقبل التطوير العقاري",
    excerpt: "How Telal Development is pioneering eco-conscious luxury, integrating LEED certification standards and smart building technologies into every project.",
    body: "Sustainability and luxury are no longer opposing concepts...",
    coverImage: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&q=80",
    category: "Sustainability",
    tags: ["sustainability", "green building", "LEED", "innovation"],
    author: "Sarah Al-Mutairi",
    readTime: 6,
    isPublished: true,
    publishedAt: new Date("2024-02-28"),
    createdAt: new Date("2024-02-25"),
  },
  {
    id: "blog-3",
    slug: "guide-to-off-plan-investment-saudi",
    title: "The Complete Guide to Off-Plan Investment in Saudi Arabia",
    titleAr: "الدليل الشامل للاستثمار على الخارطة في السعودية",
    excerpt: "Understanding the opportunities, risks, and legal framework of off-plan property investment in the Kingdom. Everything you need to know before committing.",
    body: "Off-plan investment has emerged as one of the most attractive...",
    coverImage: "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=800&q=80",
    category: "Investment",
    tags: ["off-plan", "investment guide", "legal", "tips"],
    author: "Mohammed Al-Harbi",
    readTime: 12,
    isPublished: true,
    publishedAt: new Date("2024-01-20"),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "blog-4",
    slug: "riyadh-emerging-luxury-neighborhoods",
    title: "Riyadh's Emerging Luxury Neighborhoods: Where to Invest",
    titleAr: "أحياء الرياض الفاخرة الناشئة: أين تستثمر",
    excerpt: "A deep dive into Riyadh's fastest-growing luxury districts, from the established Olaya corridor to the emerging northern suburbs.",
    body: "Riyadh's real estate landscape is transforming rapidly...",
    coverImage: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80",
    category: "Market Analysis",
    tags: ["Riyadh", "neighborhoods", "investment", "growth"],
    author: "Ahmed Al-Rashid",
    readTime: 10,
    isPublished: true,
    publishedAt: new Date("2024-03-05"),
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "blog-5",
    slug: "smart-home-technology-luxury-living",
    title: "Smart Home Technology: Elevating Luxury Living",
    titleAr: "تقنية المنزل الذكي: الارتقاء بالعيش الفاخر",
    excerpt: "How AI-powered home automation, integrated security systems, and IoT are transforming the luxury residential experience in Saudi Arabia.",
    body: "The modern luxury home is no longer defined solely by its finishes...",
    coverImage: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80",
    category: "Technology",
    tags: ["smart home", "technology", "IoT", "innovation"],
    author: "Noura Al-Dosari",
    readTime: 7,
    isPublished: true,
    publishedAt: new Date("2024-02-10"),
    createdAt: new Date("2024-02-05"),
  },
];

// ── FAQs ──────────────────────────────────────────────────
export const faqs: FAQ[] = [
  {
    id: "faq-1",
    question: "What types of properties does Telal Development offer?",
    questionAr: "ما أنواع العقارات التي تقدمها تلال للتطوير؟",
    answer: "Telal Development offers a comprehensive range of luxury properties including residential apartments, penthouses, villas, commercial office spaces, retail units, mixed-use developments, and hospitality properties. Our portfolio spans across Riyadh, Jeddah, and the Eastern Province.",
    answerAr: "تقدم تلال للتطوير مجموعة شاملة من العقارات الفاخرة تشمل الشقق السكنية والبنتهاوس والفلل والمكاتب التجارية ووحدات التجزئة والمشاريع متعددة الاستخدامات وعقارات الضيافة.",
    category: "General",
    order: 0,
    isPublished: true,
  },
  {
    id: "faq-2",
    question: "Can foreign nationals purchase property through Telal Development?",
    questionAr: "هل يمكن للأجانب شراء عقارات من خلال تلال للتطوير؟",
    answer: "Yes, under Saudi Arabia's updated property laws, foreign nationals with valid residency permits (Iqama) can purchase property for residential use. Premium Residency holders and certain investor visa holders may also purchase property. Our legal team can guide you through the specific requirements based on your nationality and residency status.",
    answerAr: "نعم، وفقاً لقوانين الملكية المحدثة في المملكة العربية السعودية، يمكن للمقيمين الأجانب الحاصلين على إقامة سارية شراء عقارات للاستخدام السكني.",
    category: "Legal",
    order: 1,
    isPublished: true,
  },
  {
    id: "faq-3",
    question: "What payment plans are available for off-plan properties?",
    questionAr: "ما خطط الدفع المتاحة للعقارات على الخارطة؟",
    answer: "Telal Development offers flexible payment plans for off-plan properties, typically structured as: 10-20% down payment at booking, staged payments linked to construction milestones, and the remaining balance upon handover. We also partner with leading Saudi banks to offer competitive mortgage solutions. Specific terms vary by project.",
    answerAr: "تقدم تلال للتطوير خطط دفع مرنة للعقارات على الخارطة، تتضمن عادةً دفعة أولى 10-20% عند الحجز، ودفعات مرحلية مرتبطة بمراحل البناء.",
    category: "Financing",
    order: 2,
    isPublished: true,
  },
  {
    id: "faq-4",
    question: "How do I schedule a property viewing?",
    questionAr: "كيف أحجز معاينة للعقار؟",
    answer: "You can schedule a property viewing through several channels: use our online booking system on the website, call our sales team at +966 53 848 6109, or send a WhatsApp message. Our dedicated agents will arrange a private viewing at your convenience, including virtual tours for international clients.",
    answerAr: "يمكنك حجز معاينة للعقار من خلال عدة قنوات: نظام الحجز عبر الإنترنت، أو الاتصال بفريق المبيعات، أو إرسال رسالة واتساب.",
    category: "Buying Process",
    order: 3,
    isPublished: true,
  },
  {
    id: "faq-5",
    question: "What is the expected ROI on Telal properties?",
    questionAr: "ما العائد المتوقع على عقارات تلال؟",
    answer: "Return on investment varies by property type and location. Historically, our residential properties have delivered 6-9% annual rental yields, while commercial properties range from 8-12%. Capital appreciation has averaged 15-25% over the construction period for off-plan investments. Past performance does not guarantee future returns.",
    answerAr: "يختلف العائد على الاستثمار حسب نوع العقار والموقع. تاريخياً، حققت عقاراتنا السكنية عوائد إيجارية سنوية 6-9%، بينما تتراوح العقارات التجارية بين 8-12%.",
    category: "Financing",
    order: 4,
    isPublished: true,
  },
  {
    id: "faq-6",
    question: "Does Telal provide property management services?",
    questionAr: "هل توفر تلال خدمات إدارة العقارات؟",
    answer: "Yes, Telal Development offers comprehensive property management services for all our developments. This includes tenant management, maintenance coordination, rental collection, and financial reporting. Our dedicated property management team ensures your investment is professionally maintained and optimized for maximum returns.",
    answerAr: "نعم، تقدم تلال للتطوير خدمات إدارة عقارات شاملة لجميع مشاريعنا. تشمل إدارة المستأجرين وتنسيق الصيانة وتحصيل الإيجارات والتقارير المالية.",
    category: "General",
    order: 5,
    isPublished: true,
  },
  {
    id: "faq-7",
    question: "What sustainability features are included in Telal projects?",
    questionAr: "ما ميزات الاستدامة المتضمنة في مشاريع تلال؟",
    answer: "All new Telal developments incorporate sustainability features including energy-efficient HVAC systems, LED lighting, water recycling systems, solar panel integration, EV charging stations, and sustainable building materials. We target LEED Silver certification or higher for all major projects.",
    answerAr: "تتضمن جميع مشاريع تلال الجديدة ميزات استدامة تشمل أنظمة تكييف موفرة للطاقة وإضاءة LED وأنظمة إعادة تدوير المياه ومحطات شحن السيارات الكهربائية.",
    category: "Sustainability",
    order: 6,
    isPublished: true,
  },
  {
    id: "faq-8",
    question: "What is the buying process timeline?",
    questionAr: "ما الجدول الزمني لعملية الشراء؟",
    answer: "The typical buying process takes 4-8 weeks from offer to completion: Week 1-2: Property selection and offer submission. Week 2-3: Due diligence, legal review, and mortgage pre-approval. Week 3-5: Contract signing and initial payment. Week 5-8: Title deed transfer and handover. Off-plan purchases follow a different timeline linked to construction milestones.",
    answerAr: "تستغرق عملية الشراء النموذجية من 4 إلى 8 أسابيع من العرض إلى الإتمام.",
    category: "Buying Process",
    order: 7,
    isPublished: true,
  },
  {
    id: "faq-9",
    question: "Are there any upcoming project launches?",
    questionAr: "هل هناك مشاريع قادمة سيتم إطلاقها؟",
    answer: "Telal Development regularly launches new projects across the Kingdom. Sign up for our newsletter to receive exclusive early access to new launches, pre-launch pricing, and VIP viewing invitations. You can also follow our social media channels for the latest announcements.",
    answerAr: "تطلق تلال للتطوير مشاريع جديدة بانتظام في أنحاء المملكة. سجل في نشرتنا الإخبارية للحصول على وصول حصري مبكر للمشاريع الجديدة.",
    category: "Projects",
    order: 8,
    isPublished: true,
  },
  {
    id: "faq-10",
    question: "What warranty and after-sales support does Telal provide?",
    questionAr: "ما الضمان ودعم ما بعد البيع الذي تقدمه تلال؟",
    answer: "All Telal properties come with a comprehensive warranty: 10-year structural warranty, 5-year MEP (mechanical, electrical, plumbing) warranty, and 2-year finishing warranty. Our dedicated after-sales team handles all warranty claims, maintenance requests, and ensures your complete satisfaction post-handover.",
    answerAr: "تأتي جميع عقارات تلال مع ضمان شامل: 10 سنوات ضمان هيكلي، 5 سنوات ضمان ميكانيكي وكهربائي وسباكة، وسنتين ضمان تشطيبات.",
    category: "General",
    order: 9,
    isPublished: true,
  },
];

// ── Testimonials ──────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    clientName: "Abdullah Al-Faisal",
    clientTitle: "CEO, Al-Faisal Holdings",
    content: "Telal Development delivered beyond our expectations. The Al Thuraya penthouse is not just a home — it's a masterpiece. Every detail reflects uncompromising quality and sophisticated design. The team's professionalism from consultation to handover was exceptional.",
    contentAr: "قدمت تلال للتطوير أكثر مما توقعنا. بنتهاوس الثريا ليس مجرد منزل — إنه تحفة فنية.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    isPublished: true,
    order: 0,
  },
  {
    id: "test-2",
    clientName: "Dr. Layla Hassan",
    clientTitle: "Consultant Surgeon",
    content: "As a first-time investor in Saudi real estate, I was impressed by Telal's transparency and guidance throughout the entire process. My apartment at Noor Residences has already appreciated significantly in value. Highly recommended for anyone seeking a trusted developer.",
    contentAr: "كمستثمرة لأول مرة في العقارات السعودية، أعجبت بشفافية تلال وتوجيههم طوال العملية بأكملها.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    isPublished: true,
    order: 1,
  },
  {
    id: "test-3",
    clientName: "Khalid Al-Otaibi",
    clientTitle: "Managing Director, Gulf Investments",
    content: "We've partnered with Telal on three commercial projects. Their commitment to quality, timely delivery, and tenant satisfaction is unmatched in the market. The Telal Business Park project is set to become the most prestigious commercial address in the Kingdom.",
    contentAr: "شاركنا تلال في ثلاثة مشاريع تجارية. التزامهم بالجودة والتسليم في الوقت المحدد ورضا المستأجرين لا مثيل له.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    isPublished: true,
    order: 2,
  },
  {
    id: "test-4",
    clientName: "Fatima Al-Zahrani",
    clientTitle: "Interior Designer",
    content: "The attention to detail in Telal's developments is remarkable. As an interior designer, I appreciate the thoughtful space planning, premium material selections, and the flexibility they offer for customization. A developer that truly understands luxury.",
    contentAr: "الاهتمام بالتفاصيل في مشاريع تلال مذهل. كمصممة داخلية، أقدر التخطيط المدروس للمساحات واختيار المواد الفاخرة.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    isPublished: true,
    order: 3,
  },
  {
    id: "test-5",
    clientName: "James Richardson",
    clientTitle: "Expat Investor, British National",
    content: "Moving to Saudi Arabia, I was cautious about real estate investment. Telal's team guided me through every legal requirement, from Iqama to title deed. Three years later, my villa in Rimal Gardens is the best investment I've made. Their after-sales support is outstanding.",
    contentAr: "عند انتقالي إلى السعودية، كنت حذراً بشأن الاستثمار العقاري. أرشدني فريق تلال خلال كل متطلب قانوني.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    isPublished: true,
    order: 4,
  },
];

// ── Team Members ──────────────────────────────────────────
export const teamMembers: TeamMember[] = [
  {
    id: "team-1",
    name: "Eng. Sayed Saber",
    nameAr: "م. سيد صابر",
    role: "Chairman",
    roleAr: "رئيس مجلس الإدارة",
    bio: "Eng. Sayed Saber is the visionary Chairman of Telal Development, leading the company's strategic direction with a bold ambition to redefine luxury real estate across the Middle East. Under his leadership, Telal has grown into one of the region's most prestigious development firms, delivering landmark projects that set new standards in quality, design, and innovation.",
    bioAr: "المهندس سيد صابر هو رئيس مجلس إدارة تلال للتطوير صاحب الرؤية، يقود التوجه الاستراتيجي للشركة بطموح جريء لإعادة تعريف العقارات الفاخرة في الشرق الأوسط. تحت قيادته، نمت تلال لتصبح واحدة من أعرق شركات التطوير في المنطقة.",
    image: "/images/chairman.png",
    linkedin: "https://linkedin.com/in/sayed-saber",
    order: 0,
  },
];

// ── Services ──────────────────────────────────────────────
export const services: Service[] = [
  {
    id: "svc-1",
    slug: "residential",
    title: "Residential Development",
    titleAr: "التطوير السكني",
    description: "From luxury apartments and penthouses to gated villa compounds, we create residential spaces that elevate everyday living. Every home is designed with meticulous attention to space, light, and premium finishes.",
    descriptionAr: "من الشقق الفاخرة والبنتهاوس إلى مجمعات الفلل المسوّرة، نصنع مساحات سكنية ترتقي بالحياة اليومية.",
    icon: "Home",
    features: ["Luxury Apartments", "Penthouses", "Gated Villa Compounds", "Smart Home Integration", "Premium Finishes"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    order: 0,
  },
  {
    id: "svc-2",
    slug: "commercial",
    title: "Commercial Development",
    titleAr: "التطوير التجاري",
    description: "Grade A office towers, business parks, and corporate headquarters designed for the modern enterprise. We deliver flexible, future-proof workspaces with cutting-edge building management systems.",
    descriptionAr: "أبراج مكتبية من الدرجة الأولى وحدائق أعمال ومقرات شركات مصممة للمؤسسات الحديثة.",
    icon: "Building2",
    features: ["Grade A Offices", "Business Parks", "Conference Centers", "Smart Building Systems", "Metro Connectivity"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    order: 1,
  },
  {
    id: "svc-3",
    slug: "mixed-use",
    title: "Mixed-Use Development",
    titleAr: "التطوير متعدد الاستخدامات",
    description: "Integrated communities that combine residential, commercial, retail, and leisure components. Our mixed-use developments create vibrant, walkable neighborhoods where people live, work, and thrive.",
    descriptionAr: "مجتمعات متكاملة تجمع بين المكونات السكنية والتجارية والتجزئة والترفيهية.",
    icon: "Layers",
    features: ["Integrated Communities", "Walkable Design", "Retail Podiums", "Landscaped Plazas", "Community Amenities"],
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    order: 2,
  },
  {
    id: "svc-4",
    slug: "off-plan",
    title: "Off-Plan Investment",
    titleAr: "الاستثمار على الخارطة",
    description: "Early access to premium developments at pre-launch pricing. Our off-plan offerings include flexible payment plans, guaranteed build quality, and strong capital appreciation potential.",
    descriptionAr: "وصول مبكر للمشاريع المميزة بأسعار ما قبل الإطلاق. تشمل عروضنا خطط دفع مرنة وجودة بناء مضمونة.",
    icon: "Map",
    features: ["Pre-Launch Pricing", "Flexible Payment Plans", "Construction Updates", "Guaranteed Quality", "Capital Growth"],
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
    order: 3,
  },
  {
    id: "svc-5",
    slug: "retail",
    title: "Retail Spaces",
    titleAr: "مساحات التجزئة",
    description: "Prime retail destinations in high-traffic locations. From flagship stores to boutique spaces, we design retail environments that enhance brand experiences and drive commercial success.",
    descriptionAr: "وجهات تجزئة مميزة في مواقع ذات حركة مرور عالية.",
    icon: "Store",
    features: ["High-Traffic Locations", "Double-Height Ceilings", "Premium Frontage", "Flexible Layouts", "Managed Parking"],
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    order: 4,
  },
  {
    id: "svc-6",
    slug: "hospitality",
    title: "Hospitality",
    titleAr: "الضيافة",
    description: "Luxury resort residences and hotel developments that deliver exceptional guest experiences and strong investor returns. Managed by international hospitality brands for hassle-free ownership.",
    descriptionAr: "مساكن منتجعات فاخرة ومشاريع فندقية تقدم تجارب استثنائية للضيوف وعوائد قوية للمستثمرين.",
    icon: "Hotel",
    features: ["Resort Residences", "Branded Hotels", "Guaranteed Returns", "Spa & Wellness", "International Management"],
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    order: 5,
  },
];

// ── Meeting Rooms ─────────────────────────────────────────
export const meetingRooms: MeetingRoom[] = [
  {
    id: "room-1",
    name: "The Boardroom",
    capacity: 16,
    amenities: ["Video Conferencing", "Whiteboard", "Coffee Service", "Sound System", "Projector"],
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    floor: 25,
    isActive: true,
  },
  {
    id: "room-2",
    name: "The Innovation Suite",
    capacity: 8,
    amenities: ["Smart TV", "Whiteboard", "Coffee Service", "High-Speed WiFi"],
    imageUrl: "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80",
    floor: 25,
    isActive: true,
  },
];

// ── Available Time Slots ──────────────────────────────────
export const timeSlots = [
  "09:00", "09:30", "10:00", "10:30", "11:00", "11:30",
  "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
  "15:00", "15:30", "16:00", "16:30", "17:00",
];
